require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/caronas", type: :request do
  
  # Carona. As you add validations to Carona, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Carona.create! valid_attributes
      get caronas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      carona = Carona.create! valid_attributes
      get carona_url(carona)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_carona_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      carona = Carona.create! valid_attributes
      get edit_carona_url(carona)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Carona" do
        expect {
          post caronas_url, params: { carona: valid_attributes }
        }.to change(Carona, :count).by(1)
      end

      it "redirects to the created carona" do
        post caronas_url, params: { carona: valid_attributes }
        expect(response).to redirect_to(carona_url(Carona.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Carona" do
        expect {
          post caronas_url, params: { carona: invalid_attributes }
        }.to change(Carona, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post caronas_url, params: { carona: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested carona" do
        carona = Carona.create! valid_attributes
        patch carona_url(carona), params: { carona: new_attributes }
        carona.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the carona" do
        carona = Carona.create! valid_attributes
        patch carona_url(carona), params: { carona: new_attributes }
        carona.reload
        expect(response).to redirect_to(carona_url(carona))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        carona = Carona.create! valid_attributes
        patch carona_url(carona), params: { carona: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested carona" do
      carona = Carona.create! valid_attributes
      expect {
        delete carona_url(carona)
      }.to change(Carona, :count).by(-1)
    end

    it "redirects to the caronas list" do
      carona = Carona.create! valid_attributes
      delete carona_url(carona)
      expect(response).to redirect_to(caronas_url)
    end
  end
end
