require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/search_caronas", type: :request do
  
  # SearchCarona. As you add validations to SearchCarona, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SearchCarona.create! valid_attributes
      get search_caronas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      search_carona = SearchCarona.create! valid_attributes
      get search_carona_url(search_carona)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_search_carona_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      search_carona = SearchCarona.create! valid_attributes
      get edit_search_carona_url(search_carona)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SearchCarona" do
        expect {
          post search_caronas_url, params: { search_carona: valid_attributes }
        }.to change(SearchCarona, :count).by(1)
      end

      it "redirects to the created search_carona" do
        post search_caronas_url, params: { search_carona: valid_attributes }
        expect(response).to redirect_to(search_carona_url(SearchCarona.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SearchCarona" do
        expect {
          post search_caronas_url, params: { search_carona: invalid_attributes }
        }.to change(SearchCarona, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post search_caronas_url, params: { search_carona: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested search_carona" do
        search_carona = SearchCarona.create! valid_attributes
        patch search_carona_url(search_carona), params: { search_carona: new_attributes }
        search_carona.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the search_carona" do
        search_carona = SearchCarona.create! valid_attributes
        patch search_carona_url(search_carona), params: { search_carona: new_attributes }
        search_carona.reload
        expect(response).to redirect_to(search_carona_url(search_carona))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        search_carona = SearchCarona.create! valid_attributes
        patch search_carona_url(search_carona), params: { search_carona: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested search_carona" do
      search_carona = SearchCarona.create! valid_attributes
      expect {
        delete search_carona_url(search_carona)
      }.to change(SearchCarona, :count).by(-1)
    end

    it "redirects to the search_caronas list" do
      search_carona = SearchCarona.create! valid_attributes
      delete search_carona_url(search_carona)
      expect(response).to redirect_to(search_caronas_url)
    end
  end
end
